export const answerListActionTypes = {
    ANSWER_SELECTED:"ANSWER_SELECTED",
    DELETING_ANSWER:"DELETING_ANSWER",
    LOADING_ANSWER_LIST:"LOADING_ANSWER",
    LOAD_ANSWER_LIST_SUCCESS:"LOAD_ANSWER_SUCCESS",
    LOAD_ANSWER_LIST_ERROR:"LOAD_ANSWER_ERROR"
}