export const dataTransferActionTypes = {
    USER_CREATED:"USER_CREATED",
    USER_UPDATED:"USER_UPDATED",
    USER_DELETED:"USER_DELETED",
    QUESTION_CREATED:"QUESTION_CREATED",
    QUESTION_UPDATED:"QUESTION_UPDATED",
    QUESTION_DELETED:"QUESTION_DELETED",
    ANSWER_CREATED:"ANSWER_CREATED",
    ANSWER_UPDATED:"ANSWER_UPDATED",
    ANSWER_DELETED:"ANSWER_DELETED"
}