export const questionListActionTypes = {
    LOADING_QUESTION_LIST:"LOADING_QUESTION_LIST",
    LOAD_QUESTION_LIST_SUCCESS:"LOAD_QUESTION_LIST_SUCCESS",
    LOAD_QUESTION_LIST_ERROR:"LOAD_QUESTION_LIST_ERROR"
}